name: Manual Trigger Workflow

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: |
          echo "Test Project"
